apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      name: activity-service
      labels:
        app: activity-service
    spec:
      containers:
        - name: activity-service
          image: baimon664/activity-service:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "mongodb+srv://Meety:Meety2022@meety.zljafpi.mongodb.net/%3FretryWrites=true&w=majority"
          resources:
            limits:
              memory: "1Gi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: activity-service
