kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: filestore-example
